name: CI

on: [push, pull_request]

jobs:
  rubies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-head, '3.0', '2.7', '2.6', '2.5' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install apt packages
        run: sudo apt-get install libsasl2-dev memcached
      - name: Install dependencies
        run: bundle install
      - name: Start Memcached
        run: ruby test/setup.rb 
      - name: Compile Gem
        run: rake compile
      - name: Run test
        run: rake test
      - name: Install gem
        run: rake install
  # TODO: OSX CI Would be nice
  # platforms:
  #   strategy:
  #     matrix:
  #       os: [macos]
  #       ruby: ['2.5']
  #   runs-on: ${{ matrix.os }}-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ matrix.ruby }}
  #     - name: Install Memcached
  #       run: brew install memcached
  #     - name: Install dependencies
  #       run: bundle install
  #     - name: Start Memcached
  #       run: ruby test/setup.rb
  #     - name: Compile Gem
  #       run: rake compile
  #     - name: Run test
  #       run: rake test
  #     - name: Install gem
  #       run: rake install
